### ISSUE TITLE
[Postprocessing] Funktionalitäten bereitstellen

### ISSUE THREAD

**Issue by ChrizZz110** [ChrizZz110/bdp-string-sim#11]
Bei der Nachverarbeitung werden die erfassten Ergebnisse validiert und inkonsistente Ergebnisse aussortiert. Zusätzlich werden die IDs den entsprechenden Entitäten zugeordnet.

Zum Besispiel könnten hier die Ergebniss der 4 Algorithmen gefiltert werden nach simmilarity > 0,7.

**Comment by ChrizZz110** [comment]
Fragwürdig ... glaube das gehört zur Evaluation.

**Comment by Lunev1** [comment]
Definition von validen Ergebnissen schwierig, Filterung findet nach Benutzereingabe bereits statt -> issue eher nicht relevant
