### ISSUE TITLE
[Processing] Tokenizer

### ISSUE THREAD

**Issue by ChrizZz110** [ChrizZz110/bdp-string-sim#5]
Ein Tokenizer muss implementiert werden, der einen String in Trigramme zerlegt. Bestenfalls sollte die Größe der N-gramme dynamisch sein (min: 2, standardmäßig 3).

Dazu eine eigene Klasse ins package preprocessing (gerne auch bessere Vorschläge)

Für einige der nachfolgenden Algorithmen ist eine Zerlegung der zu untersuchenden Zeichenkette in Trigramme notwendig. Die Zerlegung wird als Tokenisierung bezeichnet. Dabei wird die Zeichenkette in Fragmente mit 3 Buchstaben zerlegt. 
HAUS => `__H , _HA , HAU , AUS , US_ , S__` 		(Unterstriche entsprechen Platzhaltern)

**Comment by Lunev1** [comment]
Tokenizer implementiert: die Länge der Tokens kann im Konstruktor übergeben werden. Die flatMap-Funktion erzeugt dann entsprechend viele Platzhalter um den String und tokenisiert anschließend. 

Testklasse und Testdaten fehlen noch.

**Comment by ChrizZz110** [comment]
Sieht gut aus! Kannst du bitte die Klasse noch in das package 'transformation' verschieben, da es ja eine Transformations-Klasse ist. Wegen mir auch in ein neues package 'processing'. Die Testklasse hast ja schon korrekt in ein package 'processing' gepackt. 

Das Package process, hatte ich für Flink-Prozesse gedacht, z.b. createCompareCsvProcess oder calculateSimilarityProcess etc.

**Comment by ChrizZz110** [comment]
@Lunev1 : Ich denke das mit dem Tokenizer in der flatMap klappt doch nicht. Das Problem was wir nicht beachtet haben ist, dass eine FlatMap NUR auf ein Dataset angewendet werden kann, in deinem Fall auf ein DataSet<String>. Das haben wir aber nicht. Wir wollen den Tokenizer ja innerhalb unserer Map-Funktion des Algorithmus nutzen, und da steht uns mit `inputTuple.getField(1)` nur ein einfacher String zur Verfügung. Auf einen einfachen String kann keine Flatmap angewendet werden.

Dass du ein DataSet erzeugt mit dem Collector, das ist vermutlich OK! Die Frage ist nur, ob man ein DataSet mit einem Collector außerhalb einer Transformations-Funktion erzeugen kann. Denke mal nicht. Ich bin der Meinung wir sollten hier eine Funktion machen, die einen String entgegen nimmt und eine ArrayList (die hat wenigstens eine Reihenfolge) erzeugt.
Bsp. 

```
public class Tokenizer{
        public static ArrayList<String> tokenize(String input){
               …
        }
}
```

Ein weiteres Problem an dem DataSet wäre wahrscheinlich die Reihenfolge der Tupel. Ein Dataset ist meiner Meinung nach ungeordnet, heißt die Trigramme liegen wild durcheinander im Dataset. Wenn wir dann sauber mit For-Schleifen mit dem ersten Trigram beginnen wollen, können wir nicht wissen, welches Trigram im Dataset gerade an der Reihe ist.

**Comment by Lunev1** [comment]
Habe die Typen angepasst. Funktioniert jetzt mit dem Dictionary.

**Comment by ChrizZz110** [comment]
Passt. Muss jetzt natürlich wieder aus dem transformation package raus, da es ja keine flink transformation ist. Denkbar wäre ein eigenes package "commons", wo wir den Tokenizer und das Dictionary rein packen.
